### ISSUE TITLE
State Not Being Written to Variable

### ISSUE THREAD

**Issue by devmau5** [MarkAdamson/home-assistant-plugin-for-tasker#24]
I have a simple task set up that calls Get State, however when I run the task from the task screen the Get State call appears to complete without any errors but the variable is not created/updated. When I hit test entity the correct state is retrieved and appears in the pop-up.

Tested with:
- Galaxy S9 running Android 9
- Tasker 5.9.2 with Plugin 1.1.5
- Home Assistant version 0.102.3

I also noticed that the plugin does not allow you to provide a variable name with any capital letters, is there any reason for this limitation?

**Comment by MarkAdamson** [comment]
Hey,

Could you check that you have a timeout set on your Get State action? If there isn't one set, it will return instantly without populating the variable.

As for no caps being allowed: yep that's a bug.

**Comment by devmau5** [comment]
@MarkAdamson, yes I tried various timeouts (10s, 60s, 1200s), did not seem to make a difference.

**Comment by smarthkapoor** [comment]
Hi, im trying to use the home assistant plugin for tasker to get the state of some of my entities. I've been able to connect to my home assistant server, but am not able to populate my global variables with the current state. I am using timeouts and 'variable set' to transfer my task variable to a global variable. Any suggestions would be much appreciated!!

**Comment by KrX3D** [comment]
Hello, i got it working:

1. in the second box you can enter a variable which NEEDS to be lower case, also the variable is irrelevant, it does not need to exist since if it does the value isnt written to it. just input something and hit the arrow to get to the next screen.

![Screenshot_20220116-031200_Home Assistant Plug-in for Tasker](https://user-images.githubusercontent.com/18599852/149644729-09b2a864-f11a-4a15-b900-bdcd08ee2542.jpg)

2.  just hit the + sign and create a new variable (didnt try to pick one existing, since the one global and local i created before didnt show up here)

![Screenshot_20220116-031220_MacroDroid](https://user-images.githubusercontent.com/18599852/149644779-69114c35-a4e9-41ef-82d7-17392cba9ddf.jpg)

it looks like this:

![Screenshot_20220116-031256_MacroDroid](https://user-images.githubusercontent.com/18599852/149644803-542daec9-ff40-422c-9b9b-e0e37676fab2.jpg)

after testing:

![Screenshot_20220116-031200_Home Assistant Plug-in for Tasker](https://user-images.githubusercontent.com/18599852/149644815-687173bd-7ee8-4cf1-a090-0fb92d0890a5.jpg)
